### ISSUE TITLE
Add functionality to enable/disable the filter

### ISSUE THREAD

**Issue by RalphORama** [FriendosClub/ViralTweetFilter#2]
Add an option to toggle filtering of tweets to the page action "settings" form

**TODO:**
- [x] Add checkbox/switch to the page action
- [ ] Implement functionality for said checkbox (save settings / load state)
- [ ] Add enable/disable functionality to the content script
