### ISSUE TITLE
Optimize scroll event hook

### ISSUE THREAD

**Issue by RalphORama** [FriendosClub/ViralTweetFilter#5]
The current implementation hooks the `scroll` event, which gets fired rapidly and repeatedly every time the user scrolls. Should probably implement some sort of delta time checking so the hiding routine doesn't run more than once every 100ms or so.

**TODO:**
- [x] Implement delay
- [ ] Allow user to customize delay amount
   - [x] Add number input to the page action
   - [ ] Fetch the value and assign it to `filterDelay` in the content script
